// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CheckIsUserOnline(arg1:Array<string>):Promise<Record<string, boolean>>;

export function GetMessages(arg1:string,arg2:string):Promise<Array<types.MessageHist>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchUser(arg1:string):Promise<string>;

export function SendMsgBetweenUsers(arg1:string,arg2:string,arg3:string):Promise<string>;
