// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIsUserOnline(arg1) {
  return window['go']['main']['App']['CheckIsUserOnline'](arg1);
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SearchUser(arg1) {
  return window['go']['main']['App']['SearchUser'](arg1);
}

export function SendMsgBetweenUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMsgBetweenUsers'](arg1, arg2, arg3);
}
